name: Деплой бэкенда на сервер

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код
        uses: actions/checkout@v3
        
      - name: Подключаемся к серверу
        uses: appleboy/ssh-action@master
        with:
          host: 89.111.152.113
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /opt/dream-photo-ai-backend
            git pull || (git clone https://github.com/Big-Brothers-Inc/dream-photo-ai-backend.git . --depth 1)
            docker compose down
            docker compose build --no-cache
            docker compose up -d
